stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

# Build Docker image and push to GitLab Container Registry
build:
  stage: build
  image: docker:24-dind
  services:
    - name: docker:24-dind
      command: ["--insecure-registry=gitlab.wtzhome.com:5050"]
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "Logging into GitLab Container Registry (HTTP)..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin http://gitlab.wtzhome.com:5050
  script:
    - echo "Building Docker image..."
    - docker build -t http://gitlab.wtzhome.com:5050/vastiva/mediaconverter:$CI_COMMIT_SHORT_SHA -t http://gitlab.wtzhome.com:5050/vastiva/mediaconverter:latest .
    - echo "Pushing to GitLab Container Registry..."
    - docker push http://gitlab.wtzhome.com:5050/vastiva/mediaconverter:$CI_COMMIT_SHORT_SHA
    - docker push http://gitlab.wtzhome.com:5050/vastiva/mediaconverter:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG

# Deploy to production server
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to $DEPLOY_HOST..."
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
        cd /opt/vastiva
        
        # Login to GitLab Container Registry
        echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
        
        # Pull latest image
        docker pull $IMAGE_LATEST
        
        # Stop and remove old container
        docker-compose down
        
        # Start new container
        docker-compose up -d
        
        # Cleanup old images
        docker image prune -af --filter "until=24h"
        
        echo "Deployment complete!"
      ENDSSH
  environment:
    name: production
    url: https://vastiva.wtzhome.com
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
